// Generated by squad init/upgrade — do not edit
//
// Pre-merge governance check: validates that a target branch has all required
// workflows present before a PR can be opened.  Fail-closed by design.
//
// Usage (CLI):
//   node premerge-check.mjs --target-branch main --repo-root /path/to/repo [--config /path/to/config.json]
//
// Usage (API):
//   import { premergeCheck } from './premerge-check.mjs';
//   const result = premergeCheck({ targetBranch: 'main', repoRoot: '/path/to/repo', config });

import { existsSync, readFileSync, statSync } from 'node:fs';
import { join, resolve as resolvePath } from 'node:path';
import { parseArgs } from 'node:util';

// ============================================================================
// Default config path (relative to repoRoot)
// ============================================================================

const DEFAULT_CONFIG_REL = '.squad/identity/config.json';

// ============================================================================
// Config loading
// ============================================================================

/**
 * Load and parse the identity config from disk.
 * @param {string} configPath — absolute path to config.json
 * @returns {object} parsed config
 */
function loadConfig(configPath) {
  if (!existsSync(configPath)) {
    return null;
  }
  try {
    const raw = readFileSync(configPath, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse config at ${configPath}: ${err.message}`);
  }
}

// ============================================================================
// Core check
// ============================================================================

/**
 * Validate that all required workflows for `targetBranch` exist on disk.
 *
 * @param {{ targetBranch: string, repoRoot: string, config?: object }} opts
 * @returns {{
 *   branch: string,
 *   workflowRequirements: {
 *     requiredWorkflows: string[],
 *     present: string[],
 *     missing: string[]
 *   },
 *   checkPassed: boolean,
 *   reason: string
 * }}
 */
export function premergeCheck({ targetBranch, repoRoot, config }) {
  // --- Validate repoRoot ------------------------------------------------
  const root = resolvePath(repoRoot);
  if (!existsSync(root) || !statSync(root).isDirectory()) {
    throw new Error(`repoRoot does not exist or is not a directory: ${root}`);
  }

  // --- Resolve config ---------------------------------------------------
  let cfg = config ?? null;
  if (cfg === null) {
    const defaultPath = join(root, DEFAULT_CONFIG_REL);
    cfg = loadConfig(defaultPath);
  }

  // No config at all → no requirements → pass
  const branchCfg = cfg?.branches?.[targetBranch];
  const requiredWorkflows = branchCfg?.required_workflows ?? [];

  // --- Check workflows on disk ------------------------------------------
  const workflowsDir = join(root, '.github', 'workflows');
  const dirExists = existsSync(workflowsDir);

  const present = [];
  const missing = [];

  for (const name of requiredWorkflows) {
    if (dirExists && existsSync(join(workflowsDir, name))) {
      present.push(name);
    } else {
      missing.push(name);
    }
  }

  const checkPassed = missing.length === 0;
  const reason = checkPassed
    ? 'All required workflows present'
    : `Missing workflows: ${missing.join(', ')}`;

  return {
    branch: targetBranch,
    workflowRequirements: { requiredWorkflows, present, missing },
    checkPassed,
    reason,
  };
}

// ============================================================================
// CLI entry point
// ============================================================================

function cli() {
  const { values } = parseArgs({
    options: {
      'target-branch': { type: 'string' },
      'repo-root':     { type: 'string' },
      'config':        { type: 'string' },
    },
    strict: true,
  });

  const targetBranch = values['target-branch'];
  const repoRoot     = values['repo-root'];

  if (!targetBranch || !repoRoot) {
    console.error('Usage: node premerge-check.mjs --target-branch <branch> --repo-root <path> [--config <path>]');
    process.exit(2);
  }

  // Load config from explicit path if provided
  let config = undefined;
  if (values.config) {
    config = loadConfig(resolvePath(values.config));
    if (config === null) {
      console.error(`Config file not found: ${values.config}`);
      process.exit(2);
    }
  }

  const result = premergeCheck({ targetBranch, repoRoot, config });
  console.log(JSON.stringify(result, null, 2));
  process.exit(result.checkPassed ? 0 : 1);
}

// Run CLI when invoked directly
const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  import.meta.url === new URL(process.argv[1], 'file://').href;

if (isMain) {
  cli();
}
