// Generated by squad init/upgrade — do not edit
//
// Standalone token resolution for agent identity.
// Uses only Node.js built-in modules — no npm dependencies required.
//
// Usage: node .squad/scripts/resolve-token.mjs <role_slug>
// Output: installation access token on stdout, or nothing on failure (exit 0).

import { createSign } from 'node:crypto';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

// ============================================================================
// Base64url helpers
// ============================================================================

function base64url(input) {
  const b64 = Buffer.from(input).toString('base64');
  return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// ============================================================================
// Credential loading (inline from storage.ts)
// ============================================================================

/**
 * Load an app registration from `.squad/identity/apps/{key}.json`.
 * @param {string} projectRoot
 * @param {string} key
 * @returns {{ appId: number, appSlug: string, installationId: number } | null}
 */
function loadAppRegistration(projectRoot, key) {
  const regPath = join(projectRoot, '.squad', 'identity', 'apps', `${key}.json`);
  try {
    const raw = readFileSync(regPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * Load the identity config from `.squad/identity/config.json`.
 * @param {string} projectRoot
 * @returns {{ tier?: string, apps?: Record<string, { roleSlug?: string }> } | null}
 */
function loadIdentityConfig(projectRoot) {
  const configPath = join(projectRoot, '.squad', 'identity', 'config.json');
  try {
    const raw = readFileSync(configPath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

const ROLE_ALIASES = {
  lead: ['lead', 'leela', 'architect', 'architecture', 'coordinator', 'squad'],
  ralph: ['ralph'],
  backend: ['backend', 'bender', 'core', 'core-dev', 'backend-dev'],
  frontend: ['frontend', 'fry', 'ui', 'frontend-dev'],
  tester: ['tester', 'hermes', 'qa', 'test', 'observability'],
  scribe: ['scribe'],
  security: ['security', 'zapp', 'sec', 'auth', 'compliance', 'vulnerability'],
  codereview: ['codereview', 'nibbler', 'code-review', 'review'],
  docs: ['docs', 'amy', 'documentation', 'devrel', 'writer'],
  devops: ['devops', 'kif', 'platform', 'infra', 'infrastructure'],
};

/**
 * Normalize a role-like string into a lowercase slug.
 * @param {string} roleKey
 * @returns {string | null}
 */
function normalizeRoleKey(roleKey) {
  if (typeof roleKey !== 'string') return null;
  const normalized = roleKey.trim().toLowerCase().replace(/[\s_]+/g, '-');
  return normalized || null;
}

/**
 * Resolve a requested role to the configured identity role slug.
 * Uses only explicit config keys or explicit alias mappings.
 * @param {string} projectRoot
 * @param {string} roleKey
 * @returns {string | null}
 */
function resolveRoleSlug(projectRoot, roleKey) {
  const config = loadIdentityConfig(projectRoot);
  const normalized = normalizeRoleKey(roleKey);
  if (!config?.apps || !normalized) return normalized;

  if (config.tier === 'shared') {
    return config.apps.shared ? 'shared' : null;
  }

  if (config.apps[normalized]) {
    return normalized;
  }

  for (const [resolvedRole, aliases] of Object.entries(ROLE_ALIASES)) {
    if (aliases.includes(normalized)) {
      if (config.apps[resolvedRole]) {
        return resolvedRole;
      }
      // Fallback: role has an app registration file but no config.apps entry
      if (loadAppRegistration(projectRoot, resolvedRole)) {
        return resolvedRole;
      }
      break;
    }
  }

  // Final fallback: check if normalized key has an app registration file
  if (loadAppRegistration(projectRoot, normalized)) {
    return normalized;
  }

  return null;
}

// ============================================================================
// JWT generation
// ============================================================================

/**
 * Generate a JWT for GitHub App authentication (RS256, 9 min TTL).
 * @param {number} appId
 * @param {string} privateKeyPem
 * @returns {string}
 */
function generateAppJWT(appId, privateKeyPem) {
  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'RS256', typ: 'JWT' };
  const payload = {
    iss: appId,
    iat: now - 60,
    exp: now + 540,
  };

  const encodedHeader = base64url(JSON.stringify(header));
  const encodedPayload = base64url(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const signer = createSign('RSA-SHA256');
  signer.update(signingInput);
  signer.end();
  const signature = signer.sign(privateKeyPem);
  const encodedSignature = base64url(signature);

  return `${signingInput}.${encodedSignature}`;
}

// ============================================================================
// Installation token exchange
// ============================================================================

/**
 * Exchange a JWT for an installation access token via GitHub API.
 * @param {string} jwt
 * @param {number} installationId
 * @returns {Promise<{ token: string, expiresAt: Date }>}
 */
async function getInstallationToken(jwt, installationId) {
  const url = `https://api.github.com/app/installations/${installationId}/access_tokens`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${jwt}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `GitHub API error ${response.status} creating installation token: ${body}`,
    );
  }

  const data = await response.json();
  return {
    token: data.token,
    expiresAt: new Date(data.expires_at),
  };
}

// ============================================================================
// Environment variable credential resolution
// ============================================================================

/**
 * Resolve credentials from env vars: SQUAD_{ROLE}_APP_ID, _PRIVATE_KEY, _INSTALLATION_ID.
 * PEM may be base64-encoded; decoded automatically when it doesn't start with "-----BEGIN".
 * @param {string} roleKey
 * @returns {{ credentials: { appId: number, pem: string, installationId: number } | null, error: string | null }}
 */
function resolveEnvCredentials(roleKey) {
  const envKey = roleKey.toUpperCase();
  const appIdStr = process.env[`SQUAD_${envKey}_APP_ID`];
  const pemRaw = process.env[`SQUAD_${envKey}_PRIVATE_KEY`];
  const installIdStr = process.env[`SQUAD_${envKey}_INSTALLATION_ID`];

  const presentCount = [appIdStr, pemRaw, installIdStr].filter(Boolean).length;
  if (presentCount === 0) return { credentials: null, error: null };
  if (presentCount !== 3) {
    return {
      credentials: null,
      error: `Incomplete environment credentials for role "${roleKey}". Expected SQUAD_${envKey}_APP_ID, SQUAD_${envKey}_PRIVATE_KEY, and SQUAD_${envKey}_INSTALLATION_ID.`,
    };
  }

  const appId = Number(appIdStr);
  const installationId = Number(installIdStr);
  if (!Number.isFinite(appId) || !Number.isFinite(installationId)) {
    return {
      credentials: null,
      error: `Invalid environment credentials for role "${roleKey}". App and installation IDs must be numbers.`,
    };
  }

  const pem = pemRaw.trimStart().startsWith('-----BEGIN')
    ? pemRaw
    : Buffer.from(pemRaw, 'base64').toString('utf-8');

  return { credentials: { appId, pem, installationId }, error: null };
}

// ============================================================================
// Token cache (in-process, keyed by roleKey)
// ============================================================================

const tokenCache = new Map();
const REFRESH_MARGIN_MS = 10 * 60 * 1000; // 10 minutes

function clearTokenCache() {
  tokenCache.clear();
}

// ============================================================================
// High-level token resolution
// ============================================================================

/**
 * Resolve an installation access token for the given role.
 *
 * Resolution order:
 *   1. Cache (if still valid)
 *   2. Environment variables (SQUAD_{ROLE}_APP_ID / PRIVATE_KEY / INSTALLATION_ID)
 *   3. Filesystem (.squad/identity/)
 *
 * @param {string} projectRoot - Project root directory (parent of .squad/)
 * @param {string} roleKey - Role key (e.g. 'lead', 'backend', 'shared')
 * @returns {Promise<{ token: string | null, resolvedRoleKey: string | null, error: string | null }>}
 */
async function resolveTokenWithDiagnostics(projectRoot, roleKey) {
  let resolvedRoleKey = null;

  try {
    resolvedRoleKey = resolveRoleSlug(projectRoot, roleKey);
    if (!resolvedRoleKey) {
      return {
        token: null,
        resolvedRoleKey: null,
        error: `No GitHub App mapping configured for role "${roleKey}".`,
      };
    }

    // Check cache
    const cached = tokenCache.get(resolvedRoleKey);
    if (cached) {
      const remainingMs = cached.expiresAt.getTime() - Date.now();
      if (remainingMs > REFRESH_MARGIN_MS) {
        return { token: cached.token, resolvedRoleKey, error: null };
      }
      tokenCache.delete(resolvedRoleKey);
    }

    // Path 1: Environment variables (CI/CD override)
    const envResult = resolveEnvCredentials(resolvedRoleKey);
    if (envResult.error) {
      return { token: null, resolvedRoleKey, error: envResult.error };
    }
    if (envResult.credentials) {
      const jwt = generateAppJWT(envResult.credentials.appId, envResult.credentials.pem);
      const { token, expiresAt } = await getInstallationToken(jwt, envResult.credentials.installationId);
      tokenCache.set(resolvedRoleKey, { token, expiresAt });
      return { token, resolvedRoleKey, error: null };
    }

    // Path 2: Filesystem (default)
    const reg = loadAppRegistration(projectRoot, resolvedRoleKey);
    if (!reg) {
      return {
        token: null,
        resolvedRoleKey,
        error: `No app registration found for role "${resolvedRoleKey}" in .squad/identity/apps/${resolvedRoleKey}.json.`,
      };
    }

    // Check in-repo keys first, then config.keysDir, then conventional path
    const config = loadIdentityConfig(projectRoot);
    const pemName = `${resolvedRoleKey}.pem`;
    let pemPath = join(projectRoot, '.squad', 'identity', 'keys', pemName);

    if (!existsSync(pemPath)) {
      let found = false;

      // Try explicit config.keysDir
      if (config?.keysDir) {
        const extPath = join(config.keysDir, pemName);
        if (existsSync(extPath)) {
          pemPath = extPath;
          found = true;
        }
      }

      // Try conventional ~/.config/squad/*/keys/
      if (!found) {
        const squadConfigDir = join(homedir(), '.config', 'squad');
        if (existsSync(squadConfigDir)) {
          try {
            for (const owner of readdirSync(squadConfigDir)) {
              const candidate = join(squadConfigDir, owner, 'keys', pemName);
              if (existsSync(candidate)) {
                pemPath = candidate;
                found = true;
                break;
              }
            }
          } catch { /* ignore scan errors */ }
        }
      }

      if (!found) {
        return {
          token: null,
          resolvedRoleKey,
          error: `No private key found for role "${resolvedRoleKey}" at .squad/identity/keys/${resolvedRoleKey}.pem` +
            (config?.keysDir ? ` or ${config.keysDir}/${pemName}.` : ' or ~/.config/squad/*/keys/.'),
        };
      }
    }

    const pem = readFileSync(pemPath, 'utf-8');
    const jwt = generateAppJWT(reg.appId, pem);
    const { token, expiresAt } = await getInstallationToken(jwt, reg.installationId);

    tokenCache.set(resolvedRoleKey, { token, expiresAt });
    return { token, resolvedRoleKey, error: null };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { token: null, resolvedRoleKey, error: message };
  }
}

async function resolveToken(projectRoot, roleKey) {
  const result = await resolveTokenWithDiagnostics(projectRoot, roleKey);
  return result.token;
}

export { clearTokenCache, resolveRoleSlug, resolveToken, resolveTokenWithDiagnostics };

// ============================================================================
// CLI entry point
// ============================================================================

function parseCliArgs(argv) {
  const args = argv.slice(2);
  const required = args.includes('--required') || args.includes('--write');
  const positional = args.filter(arg => !arg.startsWith('--'));
  return {
    required,
    roleSlug: positional[0] ?? null,
  };
}

const isCliInvocation =
  typeof process.argv[1] === 'string' &&
  resolvePath(process.argv[1]) === fileURLToPath(import.meta.url);

if (isCliInvocation) {
  const { roleSlug, required } = parseCliArgs(process.argv);
  if (!roleSlug) {
    process.exit(required ? 1 : 0);
  }

  // Derive project root from script location (.squad/scripts/ → repo root).
  // Agents invoke this via absolute path so process.cwd() may be a worktree.
  let projectRoot = process.cwd();
  try {
    const scriptDir = dirname(fileURLToPath(import.meta.url));
    projectRoot = join(scriptDir, '..', '..');
  } catch {
    // Fallback to cwd if import.meta.url is unavailable
  }

  const result = await resolveTokenWithDiagnostics(projectRoot, roleSlug);
  if (result.token) {
    process.stdout.write(result.token);
  } else if (required) {
    console.error(result.error ?? `Failed to resolve GitHub App token for role "${roleSlug}".`);
    process.exit(1);
  }
}
